In [1]:
import numpy as np
import math
from fractions import Fraction

# Q1a. Write a program to test if a set of vectors {v1,v2,…,vn} is an orthogonal set. 

In [2]:
def ifOrthogonal(V):

    dotProduct = 0
    isOrthogonal = False
    
    for i in range(0, len(V)):
        for j in range(i+1, len(V)):
            for k in range(len(V[0])):
                dotProduct = dotProduct + V[i][k]*V[j][k]
            if dotProduct==0:
                isOrthogonal = True
            else:
                isOrthogonal = False
                print(V[i], " and ", V[j], " is not orthogonal with a dotproduct of ",dotProduct)
                return
            dotProduct = 0
            
    if isOrthogonal == True:
        print("It's an orthogonal set.")

# Q1b. Output which pairs are not orthogonal. Test it for the column vectors of A, where

In [3]:
A = [[-6,-1,3,6,2,-3,-2,1],
    [-3,2,6,-3,-1,6,-1,2],
    [6,1,3,6,2,3,2,1],
    [1,-6,-2,-1,3,2,-3,6]]

'''
A = [[-6, -3,  6,  1],
     [-1,  2,  1, -6],
     [ 3,  6,  3, -2],
     [ 6, -3,  6, -1],
     [ 2, -1,  2,  3],
     [-3,  6,  3,  2],
     [-2, -1,  2, -3],
     [ 1,  2,  1,  6]]
'''

# Check if A is an orthogonal set
ifOrthogonal(A)

It's an orthogonal set.


# Q1c. Is it always true (in executing program on dot product) that 2 vectors v.w ≠ 0 means v is not orthogonal to w? If it is not necessary true, give an example and propose a fix.

Yes, it is always true. <br>

v.w = ||v|| * ||w|| * cos(a) <br>

if v.w != 0, it means, ||v|| != 0, ||w|| != 0, cos(a) != 0 <br>

If cos(a) != 0, angle between v and w is not 90 degree.

Then, v is not orthogonal to w.

# Q2. Write a module “Orthonormalisation” that defines a a procedure orthonormalise(L) with the following specs:
•	Input: a list L of linearly independent Vecs <br>
•	Output: a list L* of len(L) orthonormal Vecs such that, for i= 1,2,…, len(L), the first i Vecs of L* and the first i Vecs of L span the same space.


Hint: Your can follow this outline or you can use your own preferred method: <br>
1.	Define orthogonalise(L) first, then call upon it,<br>
2.	Compute the list of norms of the resulting vectors, and<br>
3.	Return the list resulting from normalizing each of the vectors resulting from Step 1. <br>
4.	Display your output if  the input list of Vecs is [4,3,1,2], [8,9,-5,-5], [10,1,-1,5].


In [4]:
def norm(V):
    n = np.linalg.norm(V)
    return n


def ogScalar(a, b):
    og = np.dot(a,b)/np.dot(b,b)
    return og
    

def Orthonormalisation(L):
    
    outL=[]
    outL.append(L[0])
    # print("outL [0] is ", outL)
    
    # STEP 1: orthogonal it
    
    # loop through each vector
    for i in range(1,len(L)):
        Bi = L[i]
        
        for j in range(i):
            Bi = np.subtract(Bi, ogScalar(L[i], outL[j]) * outL[j])
            
        outL.append(Bi)   
        
    # STEP 2: Normalise it
    
    for m in range(len(outL)):
        
        outL[m] = np.true_divide(outL[m],norm(outL[m]))
        
    return outL



# Testing the functions

# Test case 1
print("Test case 1")
print()
L = np.array([[4,3,1,2], 
              [8,9,-5,-5], 
              [10,1,-1,5]])

outL = Orthonormalisation(L)

print("Original L is")
for c in range(len(L)):
    print(L[c])
print()

print("The orthonormalised vector is:")
for k in range(len(L)):
    print(outL[k])
print()


# Test Case 2
print("Test case 2")
print()

L2 =np.array([[1,0,1],
              [2,1,2],
              [1,2,0]]) 
outL2 = Orthonormalisation(L2)

print("Original L2 is")
for c in range(len(L2)):
    print(L2[c])
print()

print("The orthonormalised vector is:")
for k in range(len(L2)):
    print(outL2[k])
print()


Test case 1

Original L is
[4 3 1 2]
[ 8  9 -5 -5]
[10  1 -1  5]

The orthonormalised vector is:
[0.73029674 0.54772256 0.18257419 0.36514837]
[ 0.18677078  0.4027245  -0.56614893 -0.69455384]
[ 0.5275409  -0.6531217  -0.51230873  0.18075511]

Test case 2

Original L2 is
[1 0 1]
[2 1 2]
[1 2 0]

The orthonormalised vector is:
[0.70710678 0.         0.70710678]
[0. 1. 0.]
[ 0.70710678  0.         -0.70710678]



# Q3a. Write a program to compute the QR factorization of matrix A = QR, where Q is orthonormal and R is upper triangular. (refer to lecture notes for the theory). You may assume A consists of linearly independent vectors.

In [5]:
def qrFactorization1(A):
    Q = np.array(Orthonormalisation(A))
    print("A is ")
    print(A)
    A = A.transpose()
    R = np.dot(Q, A)

    print("Q is ")
    print(Q)

    print("R is ")
    print(R)

def qrFactorization2(A):
    Q, R = np.linalg.qr(A)
    print("A is ")
    print(A)

    print("Q is ")
    print(Q)

    print("R is ")
    print(R)

# Q3b. Compute the QR factorization of A, formed by the 3 column vectors in Q2.

In [6]:
# Test case 1
print("Test case 1")
# columns are displayed as row here, so need to take it's transpose
A =np.array([[1,0,1],[2,1,2],[1,2,0]]) 

qrFactorization1(A)
print()


# Test case 2 : from Q2
print("Test case 2")
L = np.array([[4,3,1,2], [8,9,-5,-5], [10,1,-1,5]])
qrFactorization2(L)
print()

Test case 1
A is 
[[1 0 1]
 [2 1 2]
 [1 2 0]]
Q is 
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [ 0.70710678  0.         -0.70710678]]
R is 
[[1.41421356 2.82842712 0.70710678]
 [0.         1.         2.        ]
 [0.         0.         0.70710678]]

Test case 2
A is 
[[ 4  3  1  2]
 [ 8  9 -5 -5]
 [10  1 -1  5]]
Q is 
[[-0.2981424  -0.1407365  -0.94408916]
 [-0.59628479 -0.74487369  0.29934534]
 [-0.74535599  0.65219355  0.13815939]]
R is 
[[-13.41640786  -7.00634633   3.42863757  -1.34164079]
 [  0.          -6.47387914   2.93143838   6.70386318]
 [  0.           0.          -2.57897527  -2.6941081 ]]

